name: Build and Deploy
on:
  push:
    branches:
      - rewrite

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build and Deploy
        run: npx gulp buildAndDeploy
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}